### ISSUE TITLE
Riot 13.3 is out

### ISSUE THREAD

**Issue by akontsevich** [taw00/riot-rpm#10]
Riot 13.3 is out. Is it possible to make new build or make builds more frequent please? Thanks!

New releases news feed: https://github.com/vector-im/riot-web/releases.atom

**Comment by taw00** [comment]
Updated. As for frequency... I usually let new releases sit a couple days unless it is a security fix (like 13.1). And a few days was the spread between 13.2 and 13.3 (okay a few days *2-ish). Anyway. I will try to be better about it. But expect some intermittentcy here and there.

**Comment by taw00** [comment]
I take that back. Having issues building on anything that isn't Fedora 27.

**Comment by akontsevich** [comment]
Thanks, just updated in openSUSE to newest version.

**Comment by akontsevich** [comment]
Thanks!

**Comment by akontsevich** [comment]
2 weeks without new versions - please upgrade! :)

**Comment by taw00** [comment]
Opensuse is no longer building. It's a mystery at the moment.

**Comment by akontsevich** [comment]
@taw00  Strange. I took Your `src.rpm`, latest `tar.gz` with sources, changed version in `.spec` and it was built fine for me.

**Comment by taw00** [comment]
akontsevich! Awesome. All my builds are done using Fedora's mock environment, so... that is a factor. I am glad it builds for you. I will keep troubleshooting. Maybe I will just stand up an Opensuse box just for this purpose, but that is less than ideal. I assume your platform is Tumbleweed, correct?

**Comment by akontsevich** [comment]
@taw00, yes Tumbleweed, right. Thank You very much!
