### ISSUE TITLE
Bundled libffmpeg.so and libnode.so potentially conflict

### ISSUE THREAD

**Issue by logic** [taw00/riot-rpm#11]
Bundling `libffmpeg.so` and `libnode.so` in `/usr/lib64` runs the risk of colliding with other libraries on the system (and specifically with other Electron apps that haven't mitigated this as well; I ran into this with a naive build of Signal-Desktop).

It might be worth relocating these (maybe turning `/usr/bin/riot` into a script that sets up `LD_LIBRARY_PATH` and launches the real riot executable), or better yet, see if it can be built against system libraries instead of bundling?

**Comment by taw00** [comment]
I will investigate.

**Comment by taw00** [comment]
Fixed (or adjusted really) in 0.13.5-1.taw

**Comment by taw00** [comment]
Fixed (or adjusted really) in 0.13.5-1.taw

Should be built by the time you see this.
`sudo dnf upgrade -y --refresh riot`

**Comment by logic** [comment]
So, there's still a conflict with other naïve conversions of electron apps coming from Debian:

>`file /usr/lib/.build-id/58/680ef734fdea2e9078598f1d127e8e9c80b3a7 from install of signal-desktop-1.5.2-1.fc27.x86_64 conflicts with file from package riot-0.13.5-1.taw.fc27.x86_64`

I originally thought this was [due to the use of `%defattr`](https://bugzilla.redhat.com/show_bug.cgi?id=1432372#c4), but it looks like it's a legitimate conflict between the generated `.build-id` links for what are identical libraries (in my case, with signal-desktop from the [Signal-Desktop](https://copr.fedorainfracloud.org/coprs/luminoso/Signal-Desktop/) COPR).

There's a discussion of this [on the Fedora devel mailing list](https://lists.fedorahosted.org/archives/list/devel@lists.fedoraproject.org/thread/MF4B4ASDUPBC3PFV6NLLGXXNGZY3KNVX/#3UMFFEYSIIVSBNVAFA2HX5VVSNYNJUAI), and it looks like overriding the value of the `_build_id_links` macro to either `none` (disable `.build-id` generation entirely) or `alldebug` (put them back in the debuginfo package, so they don't conflict under normal circumstances) might be a way to work around this?

(It's a problem with the other COPR as well, but it doesn't look like they do their work on Github, so I'll have to contact them elsewhere.)

Anwyay, I'm working around this right now by just force-installing the RPMs, but figured I'd mention it here just in case this is something you're concerned with (long-term, building against the shipped versions in Fedora will fix this too, so I have no idea how much effort it's worth putting in here.)

**Comment by taw00** [comment]
Interesting. To be frank, I don't really grok the build-id stuff. I will monitor this and if I find some cycles, I will look at more reasonable solutions.

**Comment by taw00** [comment]
0.13.5-2.taw now available without .build_ids. Hopefully, this resolves the issue once and for all. Reopen if it does not.
