### ISSUE TITLE
possible to add dev builds?

### ISSUE THREAD

**Issue by aoyawale** [taw00/riot-rpm#12]
is it possible you can add the 14 dev builds?

**Comment by taw00** [comment]
It's on my list. Not until after my income taxes are done. ;)

**Comment by taw00** [comment]
Okay. Income taxes still not done, but I started working on this. Builds work on my machine, but not the build system. So... "working on it"

**Comment by taw00** [comment]
DONE! 0.14.0 rc.6 is currently available. in the test repos.
Update the repo config file that is described in the README here in github, edit it, update "enabled=1" for riot-testing" and ... it should install.

I have only remedially tested the release candidate. If something breaks, lemme know.
