### ISSUE TITLE
Old version rpm

### ISSUE THREAD

**Issue by akontsevich** [taw00/riot-rpm#15]
Hi @taw00,

Where can I find 0.14.2 rpm version? 0.15.2 have serious bugs. Want to downgrade for some time. Thanks!

**Comment by taw00** [comment]
I'm assuming Fedora...
https://unix.stackexchange.com/questions/266888/can-i-force-dnf-to-install-an-old-version-of-a-package
So... `sudo dnf install riot-0.14.2-2.fc28.taw0` should do what you want, I believe.

**Comment by taw00** [comment]
Are the bugs in my packaging? Or in riot itself?

**Comment by akontsevich** [comment]
I mean I've browsed https://copr-be.cloud.fedoraproject.org/results/taw/Riot/ repo, riot-0.14.2-2.fc28.taw0 was there before, now it contains only 0.15.2 version. Is it possible to keep older versions in repo as well? Thanks!

**Comment by taw00** [comment]
Whoa. Interesting. It SHOULD be there. I wonder if COPR trims off old versions. I will ask. In the meantime, I will build it for you. What architecture do you need? And what version OS?

I will ping you in.... Riot...

**Comment by akontsevich** [comment]
> In the meantime, I will build it for you. 

Thank You very much!

>What architecture do you need? And what version OS?

@taw00 Fedora was ok, I'm subscribed to 27th version (can resubscribe to 28th if necessary), arch - x64.

>I will ping you in.... Riot...

Do You know my Riot? :)

Also could You look at my another message here, please: https://github.com/taw00/riot-rpm/issues/2#issuecomment-390239539 - it regards version 0.15.x. Thanks!

**Comment by taw00** [comment]
I rebuilt 14.2 in the copr repos

**Comment by taw00** [comment]
Note: I am attempting to build riot for opensuse.

**Comment by taw00** [comment]
I built Riot for OpenSuse Leap 15 and Tumbleweed x86_64. This was not easy because OpenSuse does some odd things. Not that it is ever easy with nodejs applications.
https://github.com/taw00/riot-rpm/commit/b81dec565190a1238cbdad31b4cf9f746fb6428d

I could not use Suse's public build platform because it is too restrictive for NPM (and probably a lot of pip applications as well). So... I am manually building these and they are tested well enough at the moment. I could use your help testing them.

Follow instructions listed here <https://github.com/taw00/riot-rpm/blob/master/README.md> and let me know where I have errored. Please. Thanks! -- I hope this solves some of your headaches. No, I do not know when I will be able to build for Leap 42.x

**Comment by akontsevich** [comment]
I'm using Tumbleweed x86_64. On this step: `sudo zypper modifyrepo -er "riot-stable-tumbleweed"` got error:

> Repo riot-stable-tumbleweed not found.

So was unable to install. And for now there is no packages here https://copr-be.cloud.fedoraproject.org/results/taw/Riot/ for openSUSE. I see rpm package provides yum repo while url should go somewhere to zypper configs - `/etc/zypp/repos.d/Riot.repo`:
```
[Riot]
enabled=1
autorefresh=1
baseurl=https://keybase.pub/toddwarner/repo/riot-opensuse/tumbleweed/x86_64/
type=rpm-md
```

**Comment by akontsevich** [comment]
Repo could be added by:
`sudo zypper ar https://keybase.pub/toddwarner/repo/riot-opensuse/tumbleweed/x86_64/ Riot`
but `sudo zypper refresh` warns that `repomd.xml` is not signed:
```

> sudo zypper refresh
Repository 'Node.js (openSUSE_Tumbleweed)' is up to date.
Retrieving repository 'Riot' metadata ---------------------------------------------------------------------------------------------------------------------------------------[/]
Warning: File 'repomd.xml' from repository 'Riot' is unsigned.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: We can't verify that no one meddled with this file, so it might not be trustworthy
    anymore! You should not continue unless you know it's safe.

File 'repomd.xml' from repository 'Riot' is unsigned, continue? [yes/no] (no): y
Retrieving repository 'Riot' metadata ...................................................................................................................................[error]
Repository 'Riot' is invalid.
[Riot|https://keybase.pub/toddwarner/repo/riot-opensuse/tumbleweed/x86_64/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'Riot' because of the above error.
```

**Comment by taw00** [comment]
I will take at the repo issues later I have to run some errands and then... attend a wedding! :)

COPR can't build OpenSuse packages. I built them myself and am hosting via a public keybase repo (hence that URL).

In the meantime, can you manually download and install the RPM found at that URL? https://keybase.pub/toddwarner/repo/riot-opensuse/tumbleweed/x86_64/ Lemme know how it goes.

**Comment by taw00** [comment]
I will take a look at the repo issues later. I have to run errands and then attend a wedding... :)
You installed this right? <https://raw.githubusercontent.com/taw00/riot-rpm/master/toddpkgs-riot-repo-1.0-3.1.testing.suse.tw20180522.taw0.noarch.rpm> ???

COPR can't build OpenSuse packages. And OpenSuse's equivalent can't build complicated nodejs-based packages. So, I build them myself and hold them on a public keybase repo.

Add this to your /etc/yum.repos.d/riot.repo file in the tumbleweed stanza (I sign packages, not the repo itself)...
```
repo_gpgcheck=0
```
And, if you are really eager, install the RPM directly. It can be found at that URL: <https://keybase.pub/toddwarner/repo/riot-opensuse/tumbleweed/x86_64/>

Let me know how it goes.

**Comment by akontsevich** [comment]
>You installed this right? https://raw.githubusercontent.com/taw00/riot-rpm/master/toddpkgs-riot-repo-1.0-3.1.testing.suse.tw20180522.taw0.noarch.rpm ???

Yes, sure.

>Add this to your /etc/yum.repos.d/riot.repo file in the tumbleweed stanza (I sign packages, not the repo itself)...

As I mentioned above I think adding `/etc/yum.repos.d/riot.repo` is wrong for openSUSE, does not work. Need to add `/etc/zypp/repos.d/Riot.repo` file with following content:

```
[Riot]
enabled=1
autorefresh=1
baseurl=https://keybase.pub/toddwarner/repo/riot-opensuse/tumbleweed/x86_64/
type=rpm-md
```

RPM installed and works fine.

**Comment by taw00** [comment]
Kewl. I will adjust my RPM tonight to put it in that location. OpenSuse's instructions state it can read stuff in /etc/yum.repos.d/ as well. I will do more research later.

**Comment by akontsevich** [comment]
Some more errors on openSUSE repo:
>Parse error: repomd.xml[39] Opening and ending tag mismatch: meta line 36 and head 

About yum: probably I had problem with it cause I have not **yum** installed - not default package management system in SUSE. Installed now. You may add `sudo zypper install yum` command to Your instructions. So now `toddpkgs-riot-repo` installed smoothly. However `sudo zypper modifyrepo -er "riot-stable-tumbleweed"` command and therefore further instructions still not work.

**Comment by akontsevich** [comment]
Hmmm, Your another dnf command works, so may fix Your instructions for openSUSE to following:
```
sudo rpm --import https://keybase.io/toddwarner/key.asc
sudo zypper install -y https://raw.githubusercontent.com/taw00/riot-rpm/master/toddpkgs-riot-repo-1.0-3.1.testing.suse.tw20180522.taw0.noarch.rpm
sudo zypper install -y dnf dnf-utils dnf-yum
dnf config-manager --set-enabled riot-stable-tumbleweed
yum install -y riot
```
This works just fine!

**Comment by akontsevich** [comment]
Modify Your instructions to following:
### Prep (OpenSuse Tumbleweed)...
```
sudo rpm --import https://keybase.io/toddwarner/key.asc
sudo zypper install https://raw.githubusercontent.com/taw00/riot-rpm/master/toddpkgs-riot-repo-1.0-3.1.testing.suse.tw20180522.taw0.noarch.rpm
zypper ar /etc/yum.repos.d/riot.repo
sudo zypper modifyrepo -er "riot-stable-tumbleweed"
```

### Install...
```
# Clean out the cache in case the change didn't get picked up
sudo zypper refresh
# Install riot
sudo zypper install riot
```
This works fine! :) Only still zypper warning about not signed `repomd.xml`, good to fix for automatic updates.

You may also add `zypper ar /etc/yum.repos.d/riot.repo` command to `toddpkgs-riot-repo-1.0-3.1.testing.suse.tw20180522.taw0.noarch.rpm` post-install script.

**Comment by taw00** [comment]
I am moving the installed repo file to /etc/zypp/repos.d/ cuz... I want to be more "correct" than "incorrect"

The challenge with adding post install scripts is that there is not definitive way to determine if you are running leap versus tumbleweed via RPM scripting. You can look at version numbers, but leap is on the path to strange versioning (42.x now?). Anyway... Moving to /etc/zypp/repos.d/ and then ...modifyrepo -er and selecting your exact type... should just work. And... right now, I believe the way I just set everything up... you don't even have to do the modifyrepo piece.

**Comment by taw00** [comment]
Closing. I think we are good. Lemme know if there are any follow-on issues.

**Comment by akontsevich** [comment]
Yes, thanks, seems updates without encryption key warning.

**Comment by taw00** [comment]
I pinged the Fedora guys. They do indeed trim old versions after 14 days at the earliest.

**Comment by akontsevich** [comment]
Again above error (in Russian now):

```
Получение метаданных репозитория "Riot for OpenSuse Tumbleweed - x86_64" ----------------------------------------------------------------------------------------------------[|]
Предупреждение: Файл "repomd.xml" из репозитория "Riot for OpenSuse Tumbleweed - x86_64" не подписан.

    Замечание: Использование подписи позволяет получателю убедиться, что данные не были изменены
    после подписи. Использование данных с некорректной/неизвестной подписью или вообще без нее может
    привести к повреждению системы и, в крайнем случае, к ее компрометации.

    Замечание: Файл "repomd.xml" — это основной индекс репозитория. Он контролирует целостность
    всего репозитория.

    Предупреждение: Мы не можем убедиться, что никто не вносил изменения в файл, поэтому доверять
    ему больше нельзя! Не продолжайте установку, если вы не уверены в безопасности этого.

Файл "repomd.xml" из репозитория "Riot for OpenSuse Tumbleweed - x86_64" не подписан, продолжить? [да/нет] (нет): нет
Получение метаданных репозитория "Riot for OpenSuse Tumbleweed - x86_64" ...............................................................................................[ошибка]
Репозиторий "Riot for OpenSuse Tumbleweed - x86_64" недействителен.
[riot-stable-tumbleweed|https://toddwarner.keybase.pub/repo/riot-opensuse/tumbleweed/x86_64/] По указанному URL-адресу не найдено допустимых метаданных
Проверьте, что URI-адреса, определенные для этого репозитория, указывают на допустимый репозиторий.
Предупреждение: Репозиторий "Riot for OpenSuse Tumbleweed - x86_64" пропускается из-за указанной выше ошибки.
Некоторые репозитории не обновлены из-за ошибки.
```

**Comment by DJViking** [comment]
Thanks for the RPM. It came in handy when Vivaldi tab with Riot crashed.
Is there a way to scale the native launched Riot? In the browser I have scaled it to 125%.

**Comment by ghost** [comment]
The RPM is no longer available.

**Comment by DJViking** [comment]
I trited the OpenSUSE Leap instructions a few days ago, it worked.

    # Snag the repository configuration (should only need to do once)
    sudo rpm --import https://keybase.io/toddwarner/key.asc
    sudo zypper install https://raw.githubusercontent.com/taw00/riot-rpm/master/toddpkgs-riot-repo-1.0-3.3.testing.suse.lp150.taw0.noarch.rpm
    sudo zypper modifyrepo -er "riot-stable-leap" // This step didn't to anything
    sudo zypper ref
    sudo zypper install riot
