### ISSUE TITLE
Tray icon on KDE is off

### ISSUE THREAD

**Issue by imaginaryusername** [taw00/riot-rpm#16]
When installing on Fedora KDE/Plasma: Instead of showing the correct "R" icon in tray that responds to  with incoming messages, a purple flat icon was shown instead. 

Following the instructions at https://github.com/vector-im/riot-web/issues/3133#issuecomment-398227872 seems to fix the issue, but it requires modification at every reinstall/upgrade. Is it possible to workaround at repo by specifying the env?

**Comment by akontsevich** [comment]
@imaginaryusername  Could You clarify please: what need to modify?

**Comment by imaginaryusername** [comment]
I'm not sure exactly what to modify else I would have made a PR. But since specifying XDG_Current_Desktop as Unity instead of KDE seems to fix the issue, I figured that the information is useful for a workaround.

**Comment by akontsevich** [comment]
@imaginaryusername seems need to fix riot.desktop file - add this line there. However did not help me for now, probably after restart or whatever. Good to remove this libappindicator3 at all :) But need it for 2 other applications - works fine without it.

**Comment by taw00** [comment]
I'm leaving this open, but I am unsure how to address it at this time.

**Comment by taw00** [comment]
Folks, if you had this problem, can you tell me the output of (from the commandline) `echo $XDG_CURRENT_DESKTOP`
? Thanks.

Right now the .desktop file is setting that to Unity before running riot. This is very wrong and has side-effects.

**Comment by akontsevich** [comment]
KDE for me.

**Comment by taw00** [comment]
> KDE for me.

So, the result of `echo $XDG_CURRENT_DESKTOP` for you is KDE?
Mind sharing the result of `env | grep XDG` ?

And you are running Fedora. Right?

I suspect that if you  edit `/usr/share/applications/riot.desktop` and change `XDG_CURRENT_DESKTOP=Unity` to `XDG_CURRENT_DESKTOP=DOESNTMATTER` .... that tray icon will remain. But if you change it to `KDE` it will disappear again, correct?

**Comment by akontsevich** [comment]
I'm running openSUSE. Correct icon only with `XDG_CURRENT_DESKTOP=Unity`. Others show purple square.

**Comment by taw00** [comment]
Hmm. Mind sharing the result of `env | grep XDG` from the commandline?

**Comment by akontsevich** [comment]
```
> env | grep XDG
XDG_VTNR=7
XDG_SESSION_ID=2
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=~/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_SESSION_DESKTOP=KDE
XDG_SESSION_CLASS=user
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_CURRENT_DESKTOP=KDE
XDG_SEAT=seat0
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
XDG_CONFIG_DIRS=/etc/xdg
```

**Comment by taw00** [comment]
Hmm. Did you hardcode anything in your .bashrc to change any of these values?

**Comment by akontsevich** [comment]
No, what's wrong with values?

**Comment by taw00** [comment]
Nothing. Just covering my bases. I am working up a more generic wrapper around riot to mitigate this, but... ugh. Electron team needs to fix their stuff.

Either that or I nuke some of the lower resolution icons, or... Anyway. I am working on something. :)

**Comment by akontsevich** [comment]
>  Electron team needs to fix their stuff.

I agree - definitely not Your stuff! :)


>Anyway. I am working on something. :)

New riot rpm version for openSUSE?! ;)

**Comment by taw00** [comment]
I have been trying to build on 15.0 today. Thus far... FAIL. Something about node_module pathing. Why!?! Clueless at the moment. It's... infuriating. There is too much "magic" in nodejs.

**Comment by akontsevich** [comment]
For me node.js clear and good enough :) I like it very much! Writing apps with it and `npm` is much easier comparing with other tools.

**Comment by Seeder101** [comment]
this is a major issue across all Distros. and from what I've read it's an electron issue even with Wire electron app as well.

**Comment by Pointedstick** [comment]
This is working properly for me now in KDE Plasma 5.15 with Riot 1.0.1. Can anyone confirm?

**Comment by imaginaryusername** [comment]
Cannot confirm - on Fedora 29 with Plasma 5.14, problem persisting even if using riot.wrapper.sh; diagnosed problem though, have to change UNITY to Unity.

**Comment by taw00** [comment]
> Cannot confirm - on Fedora 29 with Plasma 5.14, problem persisting even if using riot.wrapper.sh; diagnosed problem though, have to change UNITY to Unity.

Seriously? "Unity"? And not "UNITY"?

**Comment by imaginaryusername** [comment]
Yep, change to "Unity" and it works automagically, despite how dumb it sounds. Would recommend fixing.

**Comment by taw00** [comment]
> Yep, change to "Unity" and it works automagically, despite how dumb it sounds. Would recommend fixing.

It's in the queue.

**Comment by taw00** [comment]
Shipped! Reopen if it continues to be an issue.
And oh, by the way... EL7 is buildable again (through some ugly hackery).
