### ISSUE TITLE
Every user displays as offline

### ISSUE THREAD

**Issue by 8xEhLCqw6Kyt87PZFUtXCAugogVZE5xU** [taw00/riot-rpm#18]
Tested on Fedora. Every user (including my own account) displays as offline at all times. I don't believe this is the result of any settings within Riot, as it was like this before I configured any settings.

**Comment by MightyCreak** [comment]
I don't think it's a problem with the packaging of Riot for Fedora, but more with matrix.org. I think matrix.org disabled this feature (on their servers) to lower the load.

One way to verify if it's true would simply be to test if you have the same behaviour on the web app (https://riot.im/app/)?

**Comment by taw00** [comment]
Indeed. This is an RPM packaging repo development site. Please take this up with the riot folks (developers) if the behavior continues. https://github.com/vector-im/riot-web
