### ISSUE TITLE
Submitting debug logs doesn't work

### ISSUE THREAD

**Issue by jcgruenhage** [taw00/riot-rpm#22]
I get "Failed to send logs: No bug report endpoint has been set."

**Comment by taw00** [comment]
Yeah. Hmm. I will look into it. I have no idea how that works.

**Comment by taw00** [comment]
How did you initiate this process? With a crash? I can't find where one "sends logs".

Right now, the bug report endpoint is <https://github.com/vector-im/riot-web/issues> in the app.

**Comment by jcgruenhage** [comment]
Settings -> Help & About -> Bug reporting -> Submit debug logs

I've just switched over my workstation to Debian though (and will likely spend some time distrohopping), so I will not be of much help in investigating this :/

**Comment by taw00** [comment]
Got confirmation from the Riot dev team that sending logs works fine. It just doesn't send to _me_... it sends to _them_ which I think is probably the right answer for now.
See attached.
![Screenshot from 2019-04-08 13-46-35](https://user-images.githubusercontent.com/6908872/55745363-111d9b00-5a05-11e9-9225-10090fa35368.png)

**Comment by jcgruenhage** [comment]
It seems that was another case of my fedora doing weird things with riot, like when it stopped updating it a few months ago until I reinstalled it.. Thanks for your work!

**Comment by taw00** [comment]
Sure thing. Thank you for participating in troubleshooting!
