### ISSUE TITLE
0.9.8 has been released

### ISSUE THREAD

**Issue by TheLastProject** [taw00/riot-rpm#3]
Just in case you're not aware yet: https://github.com/vector-im/riot-web/releases/tag/v0.9.8 :)

**Comment by taw00** [comment]
I have been distracted. Thanks for the heads up. Building now.

**Comment by taw00** [comment]
Done. Lemme know how it goes.

**Comment by TheLastProject** [comment]
It mostly seems fine, aside from emojis somehow. Seeing how this packaging was done about 4 days after the 0.9.8 release, I see no bugreport for this on the official bugtracker and it works fine on the website, could this be a packaging issue? I had no problems on 0.9.7.

![2017-04-17-215528_539x201_scrot](https://cloud.githubusercontent.com/assets/1885159/25102496/fdc4a866-23b8-11e7-9d5f-d03c40f6e26e.png)

**Comment by taw00** [comment]
If there is a problem, I am sure it is my packaging that is at fault somehow. That being said, this is what I view in the desktop application after sending emoji from my android application...

![screenshot from 2017-04-18 06-17-11](https://cloud.githubusercontent.com/assets/6908872/25126306/d8e0e5ae-23ff-11e7-8443-044eccf9b61d.png)

Can you elaborate on how you sent your emoji? What platform you are on? Etc.

**Comment by AllDragonsAreDead** [comment]
I don't have problem with most emojis. So far I encountered that issue only with the atom symbol: ⚛️. When I hover the image I see `:atom_symbol:` as the alternative text. After sending a message with that Unicode character an error appears in Developer Tools:
`GET file:///opt/riot/resources/app/webapp/emojione/svg/269b-fe0f.svg?v=2.2.7 net::ERR_FILE_NOT_FOUND`

There's only one atom image in the emojione/svg folder and its name is `269b.svg`, not `269b-fe0f.svg`. Images with -abcd on the end apparently are additional (looks like color) variants of the same image. Maybe some images were removed but a script wasn't updated or vice versa?

Edit. I don't feel familiar enough with JS to debug that but one more observation:
As far as I understand, I'm pasting Unicode character with the code `0x269b`. Image `269b.svg` *does* exist in `emojione/svg` directory. The script though is requesting `269b0-fe0f.svg` which *doesn't* exist there.

Edit 2. Actually, there's no single `*-fe0f.svg` file in the `emojione/svg` directory and apparently `fe0f` indicates simply that we want emoji presentation, not text presentation: http://unicode.org/emoji/charts/emoji-variants.html Not sure how it may be related to the issue.
There's a file `/opt/riot/resources/app/webapp/bundles/6597817565d1a69c24d8/bundle.js` containing a lot of data but what may be related is a huge `e.emojioneList` array with elements like `":atom_symbol:":{unicode:["269b-fe0f","269b"],fname:"269b",uc:"269b",isCanonical:!1}`

Though, apparently it works well in web client and others using desktop clients on Linux report to not experience that issue. So I would guess, a script was not updated?

**Comment by aazhi11** [comment]
Heads up, easier said than done! Not possible at the mo ;) avlo pithu

**Comment by taw00** [comment]
I will try to dig deeper into this in a couple weeks. I am heads down at the moment with "Real Job[tm]" and this is not a critical failure. Thanks for the input.

**Comment by MightyCreak** [comment]
Now that riot-rpm 0.12.7 has been released, is this issue still relevant?

**Comment by taw00** [comment]
I don't see any more issues from my end. Closing.
