### ISSUE TITLE
Please add Fedora 32 target

### ISSUE THREAD

**Issue by eclipseo** [taw00/riot-rpm#30]
With Fedora 32 beta coming up tomorrow, could you please build Riot and Riot testing on your COPR for Fedora 32? The targets have been enabled recently by the COPR team.

**Comment by eclipseo** [comment]
Thanks!

**Comment by taw00** [comment]
Please let me know if it works for you. I do not have a F32 machine to test on and thus am flying blind.

**Comment by eclipseo** [comment]
> Please let me know if it works for you. I do not have a F32 machine to test on and thus am flying blind.

It works fine for riot-testing!

**Comment by taw00** [comment]
Thank you. I have also functional builds for Riot 1.6.0 RC3 if you are willing to test them: in the riot-testing repo. I only recommend if you want to potentially break things. I.e., I had a broken version in there for few days. In theory, it is ready for prime time, whenever the Riot guys bless it so.
