### ISSUE TITLE
OpenSUSE Leap 15.2 packaging tracker

### ISSUE THREAD

**Issue by taw00** [taw00/riot-rpm#34]
Riot needs to be packaged for Leap 15.2. This issue is here to track that progress.

**Comment by DJViking** [comment]
Thanks for still supporting OpenSUSE Leap. I can live with the old Riot 1.5, until I upgrade to Leap 15.2.

Are there any issues in building Riot 1.6 for Leap 15.2? Though not released yet.

Leap is a stable distribution which I prefer to use at work instead of the bleeding edge Tumbleweed.

**Comment by taw00** [comment]
Riot 1.6.2 is the latest and greatest and that branch no longer builds for RHEL (even RHEL8) and doesn not build on Leap 15.1. And so far, it does not build on Leap 15.2 either, but I have not given up on Leap 15.2 yet. We'll see. It hasn't been a priority since it is not officially out yet (Leap 15.2 that is).

**Comment by taw00** [comment]
There is no package option that provides for libcrypto.so.1 in Leap 15.2. With tumbleweed (and fedora), that is package libcrypto1. Leap 15.2 doesn't provide it, therefore I can't build Riot. I can't get past this requirement.

I recommend installing the flatpak instead (note, I do not maintain that, so I have no idea its quality): <https://flathub.org/apps/details/im.riot.Riot>

**Comment by DJViking** [comment]
It seems on Leap 15.1 the libcrypto.so.1 comes from the package libopenssl1_0_0
```
mintaka:/home/sverre # rpm -qil libopenssl1_0_0
Name        : libopenssl1_0_0
Version     : 1.0.2p
Release     : lp151.5.13.1
Architecture: x86_64
Install Date: sø. 16. feb. 2020 kl. 20.39 +0100
Group       : Productivity/Networking/Security
Size        : 3088816
License     : OpenSSL
Signature   : RSA/SHA256, fr. 10. jan. 2020 kl. 12.17 +0100, Key ID b88b2fd43dbdc284
Source RPM  : openssl-1_0_0-1.0.2p-lp151.5.13.1.src.rpm
Build Date  : fr. 10. jan. 2020 kl. 12.16 +0100
Build Host  : lamb09
Relocations : (not relocatable)
Packager    : http://bugs.opensuse.org
Vendor      : openSUSE
URL         : https://www.openssl.org/
Summary     : Secure Sockets and Transport Layer Security
Description :
OpenSSL is a software library to be used in applications that need to
secure communications over computer networks against eavesdropping or
need to ascertain the identity of the party at the other end.
OpenSSL contains an implementation of the SSL and TLS protocols.
Distribution: openSUSE Leap 15.1
/usr/lib64/engines-1.0
/usr/lib64/engines-1.0/libgost.so
/usr/lib64/engines-1.0/libpadlock.so
/usr/lib64/libcrypto.so.1.0.0
/usr/lib64/libssl.so.1.0.0
```

This package is also available for Leap 15.2

**Comment by taw00** [comment]
OH!!! I'm not sure why I had trouble tracking it down. I will give it a try. Thanks.

**Comment by taw00** [comment]
Well, we got beyond that issue. Now we are onto rust issues. The rust that ships with Leap 15.1 and 15.2 is out of date. At least in the context of these bugs: https://github.com/rust-lang/rust/issues/54912 and https://github.com/rust-lang/rust/issues/60602

<s>Builds for RHEL8 is having the similar problems with rust.</s>

**Comment by DJViking** [comment]
Perhaps you could try building with an additional package repository that has a newer Rust.https://download.opensuse.org/repositories/devel:/languages:/rust/openSUSE_Leap_15.2/
This has the same version of Rust that comes with Tumbleweed.

It should work fine if Rust is an BuildRequires, but if it is an Requires, then everyone who installs the RPM would need this version of rust from that repository.

**Comment by DJViking** [comment]
Where are you building it for Leap? Travis, Jenkins, SUSE OBS?
How is your build process? I could give it a try building on Leap 15.2 when I have done the upgrade.
Leap 15.2 should be out this week.

**Comment by taw00** [comment]
As of Element 1.7.1, Leap 15.2 is suddenly building. What changed? I have no idea. Closing this issue.  
_Note, Riot's name changed as of v1.7.0. Note also that I did not build a version 1.7.0, so perhaps the change happened there, or maybe in the process of release, Leap filled in some gaps._
