### ISSUE TITLE
1.6.4 for Tumbleweed?

### ISSUE THREAD

**Issue by geckolinux** [taw00/riot-rpm#35]
Hi there, is there any chance of getting 1.6.4 for Tumbleweed? My version is still stuck on 1.6.2. Thanks a lot!

**Comment by taw00** [comment]
Sorry I somehow missed this issue. It's a moot point now. We are well past 1.6.4. Current version is element-1.7.1 (there was a name change).

**Comment by geckolinux** [comment]
No problem, thanks a ton for staying on top of the package updates for openSUSE, they're greatly appreciated.
