### ISSUE TITLE
OpenSUSE versions of element seem to not perform e2ee searches

### ISSUE THREAD

**Issue by geckolinux** [taw00/riot-rpm#36]
Hi there, thanks a lot for updating to Element! (I use openSUSE Leap 15.2 and Tumbleweed.) Is there any chance you could please include this functionality in your builds?

https://github.com/vector-im/riot-web/blob/develop/docs/native-node-modules.md#adding-seshat-for-search-in-e2e-encrypted-rooms

Cheers!

**Comment by taw00** [comment]
I'll look into it. Thanks.

**Comment by taw00** [comment]
Fixed. There was an upstream error in build instructions and ... I made an error in my build script as well. Fixed in commit 22b7f09.

**Comment by geckolinux** [comment]
Awesome, thanks!

**Comment by taw00** [comment]
Actually, test it, please. Though I altered my builds and it supposedly includes native features, I see no behavior change. For example, I could do a full text search in an encrypted chatroom in the previous version.

**Comment by geckolinux** [comment]
In what version should it appear? I  currently have....
Element version: 1.7.2
olm version: 3.1.3
... but searching returns no results, as in prior versions.

**Comment by taw00** [comment]
element-1.7.2-2.fc32.taw.x86_64

Search returns results just fine for me. I will pick through the SUSE builds to see if I see some error in there, but ...

Okay, I picked through the builds and I see no issues in either the 15.2 or Tumbleweed builds and they look identical to the Fedora 32 build. Do you see this problem in both 15.2 and Tumbleweed?

**Comment by geckolinux** [comment]
> element-1.7.2-2.fc32.taw.x86_64

Hmm OK, I have 1.7.2-2.suse.tw.taw , but no search results.

Did you have to enable any settings perchance?

> Do you see this problem in both 15.2 and Tumbleweed?

Haven't tried it yet on Leap.

**Comment by geckolinux** [comment]
> Did you have to enable any settings perchance?

I just found this under the **Security and Privacy** section:

> #### Message search
> Element is missing some components required for securely caching encrypted messages locally. If you'd like to experiment with this feature, build a custom Element Desktop with search components added.

**Comment by taw00** [comment]
Hmm. sqlcipher is a requirement. Did that get installed?

**Comment by geckolinux** [comment]
> sqlcipher is a requirement. Did that get installed?

Ah, OK. Yes, I had `sqlcipher` installed, but I just now installed additionally `libsqlcipher-3_30_1-0`, that was the missing package. I imagine that version number will change constantly, so it might be good to add `tcl-sqlcipher` as a dependency, which also pulls in `libsqlcipher-3_30_1-0` and I assume will be updated by the maintainer according to the latest version numbers of `libsqlcipher-3_*`

Thanks so much for enabling this feature, it's extremely important and useful for me. Seems to work great now.

**Comment by taw00** [comment]
Leaving this bug open until I figure out how to package this correctly.
Can you please do an `rpm -ql libsqlcipher-3_30_1-0` please and post the results here?
And can you do the same for `sqlcipher`?

Nevermind, I looked them up. `sqlcipher-devel` provides `/usr/lib64/libsqlcipher.so` Can you try it with that package instead of the other and let me know if that resolves things?

**Comment by geckolinux** [comment]
Sure, sorry for the closing it prematurely.

```
~> rpm -ql libsqlcipher-3_30_1-0
/usr/lib64/libsqlcipher-3.30.1.so.0
/usr/lib64/libsqlcipher-3.30.1.so.0.8.6
/usr/share/doc/packages/libsqlcipher-3_30_1-0
/usr/share/doc/packages/libsqlcipher-3_30_1-0/README.md
/usr/share/licenses/libsqlcipher-3_30_1-0
/usr/share/licenses/libsqlcipher-3_30_1-0/LICENSE
```

```
~> rpm -ql sqlcipher
/usr/bin/sqlcipher
/usr/share/doc/packages/sqlcipher
/usr/share/doc/packages/sqlcipher/README.md
/usr/share/licenses/sqlcipher
/usr/share/licenses/sqlcipher/LICENSE

**Comment by geckolinux** [comment]
> Nevermind, I looked them up. `sqlcipher-devel` provides `/usr/lib64/libsqlcipher.so` Can you try it with that package instead of the other and let me know if that resolves things?

It looks like `sqlcipher-devel` simply requires `tcl-sqlcipher` and `libsqlcipher-3_30_1-0` again as dependencies. I'd say that just  `tcl-sqlcipher` should be good enough.

**Comment by taw00** [comment]
Ugh. So ugly to require a TCL language package for something that is not TCL-related.

**Comment by taw00** [comment]
Give the new build about 30 minutes to finish and v1.7.2-3 should be available. Please remove the tcl-sqlcipher rpm before updating and let's see if this new build pulls it back in. Thanks for your troubleshooting. Once confirmed, I will close this issue down.

**Comment by geckolinux** [comment]
> Ugh. So ugly to require a TCL language package for something that is not TCL-related.

Ah, I see now what you mean. I can try to file an openSUSE bug report. What would be more sane, to change the `libsqlcipher-3_30_1-0` package name to just `libsqlcipher`? Or include `/usr/lib64/libsqlcipher.so` in the `sqlcipher` package?

> Please remove the tcl-sqlcipher rpm before updating and let's see if this new build pulls it back in. 

Worked great, thanks a lot!

This should probably be a separate issue, but the past few releases of the `element` package have been making zypper / YaST complain that the package fails the integrity check, I imagine the signature changed?

**Comment by taw00** [comment]
> Ah, I see now what you mean. I can try to file an openSUSE bug report. What would be more sane, to change the libsqlcipher-3_30_1-0 package name to just libsqlcipher? Or include /usr/lib64/libsqlcipher.so in the sqlcipher package?

Fedora includes the library with sqlcipher and another library (not sure if they are the same) with sqlcipher-devel. I think ubuntu does this as well. I don't know what the right packaging is, but linked to TCL is bizarre. Probably some historical reason. Yeah a bug to reexamine it would be nice.

> This should probably be a separate issue, but the past few releases of the element package have been making zypper / YaST complain that the package fails the integrity check, I imagine the signature changed?

Maybe. Send me an email (t0dd AT protonmail.com) with your .repo file and I will look to see what may be going on.

Closing this issue as resolved.

**Comment by taw00** [comment]
New version built and delivered using `sqlcipher-devel` as the required RPM. Lemme know if this resolves the issue (again, but differently).
https://github.com/taw00/element-rpm/commit/24da4cc812feda296fd31fc22719e51f0429ce3b

**Comment by geckolinux** [comment]
Hi there, searching has stopped working again on Tumbleweed, but it's a new issue this time:

> Element can't securely cache encrypted messages locally while running in a web browser. Use Element Desktop for encrypted messages to appear in search results.

It appears to be having self-awareness issues? :-)

Thanks for the help!
