### ISSUE TITLE
Fedora 33 is available in copr

### ISSUE THREAD

**Issue by eeickmeyer** [taw00/riot-rpm#38]
Hi there!

I know that beta is coming up in quite a while, but Fedora 33 branched about a month ago and is available in copr.

So, my question is, do you mind flipping the switch in your copr to get F33 builds going?

Thanks!

**Comment by damnms** [comment]
i am on 33 beta now and unfortunately, no updates here :/

**Comment by luminoso** [comment]
Same here. However you can grab the f32 build at https://copr.fedorainfracloud.org/coprs/taw/element/builds/ while it is not available for f33

**Comment by damnms** [comment]
i use now the flatpak version, works fine

**Comment by eeickmeyer** [comment]
Except the flatpak version cannot attach local files to messages (really a shortcoming of flatpak).
