### ISSUE TITLE
HEADS UP: Having issues with build 0.9.9

### ISSUE THREAD

**Issue by taw00** [taw00/riot-rpm#4]
Working on this build but I am having issues where the application comes up but just gives me a blank white box. And then when I downgrade, that issue remains -- so it silently hoses my environment for whatever reason. Please be patient. I'm working on it.

And yes, I immediately pulled the build so you shouldn't see it.

**Comment by jcgruenhage** [comment]
0.9.10 has been released, maybe try that one?

**Comment by MightyCreak** [comment]
I don't know if you have this bug @taw00, but some smileys doesn't work anymore (GNOME, Fedora 25)

**Comment by MightyCreak** [comment]
Do you have any heads up on this issue @taw00 ?

Thanks ;)

**Comment by AllDragonsAreDead** [comment]
@MightyCreak – Probably related to: https://github.com/taw00/riot-rpm/issues/3#issuecomment-294575477

**Comment by taw00** [comment]
Folks... Some know. Some don't know.  But I took a lengthy leave of absence from both corporate life and the world of technology. I am easing my way back in to technology, but probably done with corporate life. We'll see.

Anyway... I updated builds to 0.12.6 -- lemme know if there are issues.
