### ISSUE TITLE
Wrong libsqlcipher version for Tumbleweed

### ISSUE THREAD

**Issue by geckolinux** [taw00/riot-rpm#41]
Hi there, after the fix in #36 search was working great, but recently it looks like Tumbleweed upgraded its `libsqlcipher` to `libsqlcipher-3.31.0.so.0` while Element is still expecting `libsqlcipher-3.30.1.so.0`. 

As a workaround I manually installed this RPM for now:
http://mirror.dal10.us.leaseweb.net/opensuse/history/20201002/tumbleweed/repo/oss/x86_64/libsqlcipher-3_30_1-0-4.3.0-1.4.x86_64.rpm

Thanks for maintaining Element for openSUSE!

**Comment by taw00** [comment]
New version built and delivered using `sqlcipher-devel` as the required RPM. Lemme know if this resolves the issue (again, but differently).
https://github.com/taw00/element-rpm/commit/24da4cc812feda296fd31fc22719e51f0429ce3b

**Comment by geckolinux** [comment]
That did the trick, thanks very much for the quick fix!

**Comment by geckolinux** [comment]
@taw00  Hi there, sorry, it's me again with the search issue. ;-)

Now it's complaining that it can't find `libsqlcipher-3.31.0.so.0`. The Tumbleweed version has been bumped to `libsqlcipher-3.33.0.so.0`. So I was able to trick it into working for now with:

`sudo ln -s /usr/lib64/libsqlcipher-3.33.0.so.0 /usr/lib64/libsqlcipher-3.31.0.so.0`

**Comment by taw00** [comment]
I'm not sure what the right answer for that is. So specific. Hmm. Maybe I need to be version specific in the spec file. But that would be . . . unfortunate.

**Comment by geckolinux** [comment]
I guess that's more of an Element issue. Maybe an Element bug report?

**Comment by taw00** [comment]
Maybe. I will dig into it when I get a moment.

**Comment by felixx9** [comment]
my Element Desktop (@ fedora 35) tells me:

`Error opening the database: SqlCipherError("Sqlcipher support is missing")`

Does this have something to do with that?
![Screenshot from 2021-11-08 17-47-49](https://user-images.githubusercontent.com/51174875/140810533-9c99dc88-ad86-4d7b-a142-1b9b65f11c41.png)

**Comment by felixx9** [comment]
And last build failed:
![Screenshot from 2021-11-08 21-52-35](https://user-images.githubusercontent.com/51174875/140816377-ae53302f-a723-42e1-bf0d-e18596ad8506.png)

**Comment by taw00** [comment]
Well ... hell ... lemme investigate.
@felixx9 ...
- those sqlcipher packages were build in support of CentOS 8. Fedora and OpenSUSE ship with it.
- that failed build was for OpenSUSE Tumbleweed only. Which is since built successfully.

Can you do me a favor and give me the results of this?
```
rpm -qa | grep sqlcipher
sudo dnf list | grep sqlcipher
rpm -q element
rpm -q element --requires
```

Thanks. -t

**Comment by felixx9** [comment]
Hej taw00
oh this issue is closed - didn't see that before. Anyway - thx for reply. And no problem at all:

```
[hof@dlxps15 ~]$ rpm -qa | grep sqlcipher
sqlcipher-4.4.3-2.fc35.x86_64
[hof@dlxps15 ~]$ sudo dnf list | grep sqlcipher
[sudo] password for hof: 
sqlcipher.x86_64                                                                         4.4.3-2.fc35                                                     @fedora                                    
libgda-sqlcipher.x86_64                                                                  1:5.2.10-2.fc35                                                  fedora                                     
rust-libsqlite3-sys+sqlcipher-devel.noarch                                               0.20.1-3.fc35                                                    fedora                                     
rust-rusqlite+sqlcipher-devel.noarch                                                     0.24.2-2.fc35                                                    fedora                                     
sqlcipher.i686                                                                           4.4.3-2.fc35                                                     fedora                                     
sqlcipher-devel.i686                                                                     4.4.3-2.fc35                                                     fedora                                     
sqlcipher-devel.x86_64                                                                   4.4.3-2.fc35                                                     fedora                                     
[hof@dlxps15 ~]$ rpm -q element
element-1.9.4-1.fc35.taw.x86_64
[hof@dlxps15 ~]$ rpm -q element --requires
/bin/sh
/bin/sh
/usr/bin/bash
ld-linux-x86-64.so.2()(64bit)
ld-linux-x86-64.so.2(GLIBC_2.2.5)(64bit)
ld-linux-x86-64.so.2(GLIBC_2.3)(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
rtld(GNU_HASH)
sqlcipher
[hof@dlxps15 ~]$ 

```

**Comment by taw00** [comment]
Good. You should be good to go then.
Cheers. -t

**Comment by felixx9** [comment]
Didn't work until this morning. Today lot's of new Updates installed > seems to work fine now. Thx anyway!
