### ISSUE TITLE
Can't search encrypted messages

### ISSUE THREAD

**Issue by kotomaran** [taw00/riot-rpm#42]
There is a tooltip in the search UI:
> Use the Desktop app to search encrypted messages

and search returns no results in an encrypted room. Isn't it the Desktop app?

**Comment by geckolinux** [comment]
Same issue here.
https://github.com/taw00/element-rpm/issues/36#issuecomment-747816750

Reported here:
https://github.com/vector-im/element-web/issues/16091

**Comment by geckolinux** [comment]
Two possible issues,  both with workarounds:

- https://github.com/vector-im/element-web/issues/14229#issuecomment-745276193
- https://github.com/taw00/element-rpm/issues/41#issuecomment-770462833
