### ISSUE TITLE
Use openSUSE OBS to build packages?

### ISSUE THREAD

**Issue by geckolinux** [taw00/riot-rpm#44]
Hi there,

Thanks very much for providing RPMs thus far for Element, it's extremely important for me. Have you considered using the openSUSE Build Service instead of Github? It will let you build RPMs and repositories for openSUSE and Fedora and even DEBs, and it has a huge set of mirror servers.

Thanks a lot!

**Comment by taw00** [comment]
I have looked at it, but I am Fedora first, so I use COPR instead. Debs ... I don't care about. I leave those to someone else.
Thus I build for CentOS, RHEL, Fedora, and OpenSUSE Tumbleweed and 15.2 (as of the time of comment).
