### ISSUE TITLE
Encrypted message search broken due to sqlcipher linking conflict (with workaround)

### ISSUE THREAD

**Issue by Skirmisher** [taw00/riot-rpm#51]
In short, GTK3 depends on sqlite by way of its "Tracker" indexing component, which conflicts with Element trying to link to sqlcipher, since sqlcipher uses the same symbols as sqlite. This causes encrypted message search to fail to initialize, and the settings page displays the message `Error opening the database: SqlCipherError("Sqlcipher support is missing")`.

This can be worked around by specifying libsqlcipher in `LD_PRELOAD`, as described in the [Element issue](https://github.com/matrix-org/seshat/issues/102#issuecomment-943311270). On Fedora 35, I have added `LD_PRELOAD=/usr/lib64/libsqlcipher-3.34.1.so.0` to my copy of `/usr/bin/io.element.element.wrapper.sh`. (Note that after doing this, I got an "invalid passphrase" error instead of a "missing sqlcipher" error and had to reset the database anyway, but after that it worked fine.)

**Comment by golanv** [comment]
I can confirm this.  I'm having the same issue on Fedora 35, and running the suggested workaround gets message searching forking again.
