### ISSUE TITLE
Unable to install on Fedora 35

### ISSUE THREAD

**Issue by HNGamingUK** [taw00/riot-rpm#52]
Hello,

I have recently moved computers over and thus installed a fresh Fedora 35. I attempted to install by entering the required commands: 

```
sudo dnf install -y dnf-plugins-core distribution-gpg-keys
sudo dnf copr enable taw/element
sudo dnf install -y element --refresh
```
However when running the final command to install element, it does no install and outputs the following:
```
No match for argument: element
Error: Unable to find a match: element
```

I can confirm the copr repo is there and is enabled. 
![image](https://user-images.githubusercontent.com/5269015/148676265-5d8c25c8-ca58-4d0d-b51f-e742e1b9f71f.png)

I did notice the following note on the copr site but not on this git repo
![image](https://user-images.githubusercontent.com/5269015/148676319-3431015d-f7db-4041-863b-14f23ac9b1fc.png)

If you require any further details do let me know.

**Comment by pixelplanetdev** [comment]
It's annoying that those instructions are still in the README.md and on the element.io website itself.
If it doesn't exist anymore, please consider removing those instructions or mentioning the licencing issues of Electron.

**Comment by Athwale** [comment]
What are the possible solutions for the licensing issue?

**Comment by iGeorgeX** [comment]
Maybe Spectral [https://gitlab.com/spectral-im/spectral](url) or Nheko [https://github.com/Nheko-Reborn/nheko](url)  is an alternativ?

**Comment by Athwale** [comment]
Spectral is in Alpha and the development seems dead or slow. Nheko seems more active and is available on fedora. Might be a good choice until this issue is fixed.

**Comment by Athwale** [comment]
Is the previous Element fc34 rpm available for download anywhere?

I have been using Nheko as an alternative matrix client for a few weeks and I have had several segfaults. It is bad at handling gifs and mp4, the emoji function is also broken, encryption seems to be buggy as well. The user interface is not finished and several features supported by Element do not work at all.

I also suggest contacting Element over email or their support channel and asking them to help the developer solve the issues or make their own rpm package.
