### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by drahnr** [taw00/riot-rpm#55]
Thank you for 2 years of convenience that I and many others enjoyed, if you ever happen to be somewhere close to Munich/Germany, I'd be happy to buy you a beer. Packaging electron is a giant PITA.

Thank you! 

Cheers :beers:

**Comment by eclipseo** [comment]
Thanks too, your COPR was great for those of us who prefer traditional RPM!
Thanks for your hard work!

**Comment by taw00** [comment]
Thank you guys. It's nice to hear this.
