### ISSUE TITLE
Please publish fingerprint for key ID 4f38bde2

### ISSUE THREAD

**Issue by janvlug** [taw00/riot-rpm#7]
I'm on Fedora 26. I tried to install riot with:

dnf copr enable taw/Riot
dnf install distribution-gpg-keys-copr
dnf install riot.x86_64

The last command results in the question whether I want to import GPG key 0x4F38BDE2 from https://copr-be.cloud.fedoraproject.org/results/taw/Riot/pubkey.gpg. Also the fingerprint of key 0x4F38BDE2 is presented.

I would expect to be able to verify this fingerprint somewhere on the internet on one of the riot pages, or on the wiki of this project.

Could you please publish the fingerprint for GPG key 0x4F38BDE2?

**Comment by taw00** [comment]
That is a copr generated GPG key... I will see if I can dig up any information on it.

**Comment by taw00** [comment]
Fingerprint added to description of the repository here: https://copr.fedorainfracloud.org/coprs/taw/Riot/
And the two `*.repo` files found here:  https://github.com/taw00/riot-rpm
